# config/featured_recipes.yml
popular:
  - slug: curry
    title: カレー
    image_asset: curry.png
    time: 30分
    overall: 5
    level: 5
    comment: 玉ねぎをしっかり炒めるのがコツ。
    material: 玉ねぎ/人参/じゃがいも/牛こま/市販ルウ
    recipe: 野菜を炒める→水と一緒に煮る→ルウを溶かす→仕上げ

  - slug: hamburg
    title: ハンバーグ
    image_asset: hamburg.png
    time: 25分
    overall: 5
    level: 3
    comment: タネは粘りが出るまでよく混ぜる。
    material: 合挽き/玉ねぎ/卵/パン粉/牛乳/塩胡椒
    recipe: 玉ねぎ炒め→タネ作り→成形→焼き→蒸し焼き

  - slug: karaage
    title: 唐揚げ
    image_asset: karaage.png
    time: 20分
    overall: 5
    level: 3
    comment: 二度揚げで外カリ中ジューシー。
    material: 鶏もも/醤油/酒/生姜/にんにく/片栗粉
    recipe: 漬け込み→粉をまぶす→低温で揚げる→高温で仕上げ
recommended: []

recommended:
  - slug: chahan
    title: シンプルで簡単チャーハン！
    image_asset: chahan.png
    time: 20分
    overall: 4
    level: 5
    comment: 和えるだけの副菜。シンプルな基本のチャーハンのご紹介です。材料も少なく、作り方も簡単。ポイントは長ねぎと卵を先に炒め、ごはんは後から入れること。強火でさっと仕上げてくださいね。パラっとおいしい定番のチャーハンをぜひ作ってみてくださいね。
    material: ごはん
              200g
              長ねぎ
              5cm
              溶き卵 (Mサイズ)
              1個分
              (A)
              しょうゆ
              小さじ1
              鶏ガラスープの素
              小さじ1/2
              塩こしょう
              ふたつまみ
              ごま油
              大さじ1
              小ねぎ (小口切り)
              適量
    recipe: 1長ねぎはみじん切りにします。

            ポイント
            長ねぎのみじん切りはこちらを参考にしてくださいね。

            2
            フライパンを中火で熱してごま油をひき、1を入れて炒めます。しんなりしたら溶き卵を入れて炒めます。

            3
            卵に火が通ったらごはんを入れて強火で炒めます。ごはんがほぐれたら(A)を入れてさっと炒め合わせます。
          
           ポイント
            パラパラに仕上げるには、ごはんを加えた後、強火で手早く炒めるのがポイントです。

            4
            全体がなじんだら火から下ろします。お皿に盛り付け、小ねぎをかけて完成です。

  - slug: chiken saute
    title: 難しい工程は一切ないチキンソテー
    image_asset: chiken saute.png
    time: 15分
    overall: 5
    level: 5
    comment: 難しい工程は一切ない鶏もも肉のポン酢ソテーをご紹介♪鶏もも肉を焼いてポン酢とからめるだけで簡単に作れます。味付けはポン酢だから失敗知らずな一品です。ジューシーで柔らかい鶏もも肉を使って是非作ってみてください！
    material: 材料 【1人分】
              鶏もも肉
              1枚(200g)
              塩こしょう
              少々
              薄力粉
              適量
              サラダ油
              大さじ1/2
              
              ☆調味料
              酒
              大さじ1
              砂糖
              小さじ2
              ポン酢しょうゆ
              大さじ1
    recipe: 1鶏肉は厚みが均等になるように開き、両面に塩こしょう、薄力粉をふる。

            2フライパンにサラダ油を入れて熱し、鶏肉を皮目を下にして入れる。焼き色がつくまで中火で焼き、上下を返して肉に火が通るまで弱火で5分程度焼く。

            3☆を加えて全体に絡める。
    
  - slug: neapolitan
    title: ワンパンで作る!簡単ナポリタン
    image_asset: neapolitan.png
    time: 20分
    overall: 4
    level: 5
    comment: フライパンを使って一人分のナポリタンを作ります。洗い物も少なく、簡単に作れるのが嬉しいレシピ♪また牛乳なしで作れるレシピでもあります。ピーマンが苦手な場合はなしでもOK！
    material: 材料 【1人分】
              スパゲティ[1.6mm]
              80g
              ソーセージ
              2本(40g)
              玉ねぎ
              1/4個(50g)
              ピーマン
              1個(30g)
              オリーブオイル
              大さじ1
              ケチャップ
              大さじ3
              ☆調味料
              水
              400cc
              塩
              ひとつまみ
              こしょう
              少々
              コンソメ
              小さじ1/2
    recipe: 1玉ねぎは薄切りにする。ピーマンは縦半分に切って種とわたを取り除き、縦5mm幅に切る。

            2ソーセージは斜め1cm幅に切る。

            3フライパンにオリーブオイルを入れて中火で熱し、玉ねぎ、ソーセージを入れて玉ねぎがしんなりするまで炒める。

            4☆を加え、スパゲティを半分に折り入れて混ぜる。煮立ったらふたをし、時々混ぜながら袋の表示時間通りゆでる。

            ポイント今回は1.6mm、ゆで時間7分のスパゲティを使用しています。レシピより太い麺をお使いの場合は様子をみて水分を追加し、調整しましょう。ゆでている間は麺がくっつかないように時々混ぜましょう！

            5ピーマン、ケチャップを加え、混ぜながら強めの中火で汁気をとばして煮詰める。

